### ISSUE TITLE
Feature Request : Support for GSSAPI on the new namespace

### ISSUE THREAD

**Issue by segui** [vt-middleware/ldaptive#105]
Hi,

After discussion on cas-user list, it appears that GSSAPI can't be used with CAS 4x as it was on CAS 3 [1] because of lack of support on the namespace DSL although ldaptive supports GSSAPI. It would be great to have this !

Thanks,
Christophe.

[1] https://wiki.jasig.org/pages/viewpage.action?pageId=10650669

**Comment by dfish3r** [comment]
The 1.2-SNAPSHOT should support this via the ```sasl-bind-search-authenticator```.

**Comment by dfish3r** [comment]
Feature supported in the next release.
