### ISSUE TITLE
Make password attribute configurable

### ISSUE THREAD

**Issue by rkorn86** [vt-middleware/ldaptive#111]
Instead of hardcoding the `userPassword` attribute in https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/auth/AbstractCompareAuthenticationHandler.java#L67 it would be better to make it configurable. Our company uses different passwords for different services and allow password reading via ACL for different manager binds. So this is a real scenario.

**Comment by rkorn86** [comment]
@dfish3r: @mmoayyed suggested me to write to you, because i implemented a solution for this issue inside Apereo CAS. Having the fix upstream is much better, but I dont understand the ldaptive code very well. I did not find the exact point how to extend your XSL Schema. The following pull request will show, how far I got. Hopefully helpfull.

**Comment by rkorn86** [comment]
@dfish3r do you have any plan, when 1.2 will be finally released or can say, which fixes are missing for a 1.2 release?

**Comment by dfish3r** [comment]
I'm hopeful I can get it done next week.

**Comment by dfish3r** [comment]
v1.1 fixed at https://github.com/vt-middleware/ldaptive/commit/b7b45d94658a7804393dd940b9386b0bc6c344c7

v1.0 fixed at https://sourceforge.net/p/ldaptive/code/3153/
