### ISSUE TITLE
IdlePruneStrategy requires a Duration > 0

### ISSUE THREAD

**Issue by rodwiddowson** [vt-middleware/ldaptive#113]
As noted in https://issues.shibboleth.net/jira/browse/IDP-1043 if you summon up an IdlePruneStratefy with a duration of zero you get an IllegalArgumentException

Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:562)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:695)
	at org.ldaptive.pool.AbstractConnectionPool.initialize(AbstractConnectionPool.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Which corresponds to this line (257) in mainline 

    poolExecutor.scheduleAtFixedRate(
      () -> {
        logger.debug("begin prune task for {}", AbstractConnectionPool.this);
        try {
          prune();
        } catch (Exception e) {
          logger.error("prune task failed for {}", AbstractConnectionPool.this);
        }
        logger.debug("end prune task for {}", AbstractConnectionPool.this);
      },
      getPruneStrategy().getPrunePeriod().getSeconds(),
      getPruneStrategy().getPrunePeriod().getSeconds(),
      TimeUnit.SECONDS);

It seems to me that all the PruneStragies need to test against zero durations and die appropriately.  The net result for my customer would be the same but it might make the failure easier for them to diagnose.

I can pull together a PR if it would help

**Comment by dfish3r** [comment]
Easy enough.
I'll note that those tasks could also support fractions of a second.
That sort of configuration seemed ridiculous at the time, but I didn't foresee this pain point.

**Comment by dfish3r** [comment]
1.0.x patched at https://sourceforge.net/p/ldaptive/code/3157/
