### ISSUE TITLE
'http://www.ldaptive.org/schema/spring-ext' is not available for visit

### ISSUE THREAD

**Issue by digevil** [vt-middleware/ldaptive#116]
my bean header:

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:sec="http://www.springframework.org/schema/security"
       xmlns:ldaptive="http://www.ldaptive.org/schema/spring-ext"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
       http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.2.xsd
       http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-3.2.xsd
       http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd
       http://www.ldaptive.org/schema/spring-ext http://www.ldaptive.org/schema/spring-ext.xsd">

and throw me an exception:

But for our having caught this error, the web application context would not have initialized.>
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.ldaptive.org/schema/spring-ext]

i then try visit this location but got 404.

**Comment by dfish3r** [comment]
http://www.ldaptive.org/schema/spring-ext.xsd is working for me.
Perhaps you were having network issues or github was having issues?

**Comment by dfish3r** [comment]
No response from reporter.
