### ISSUE TITLE
AbstractCompareAuthenticationHandler uses the wrong format string when PasswordScheme contains a "-" character

### ISSUE THREAD

**Issue by binsys** [vt-middleware/ldaptive#121]
In class AbstractCompareAuthenticationHandler
passwordScheme = "SHA-256"

https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/auth/AbstractCompareAuthenticationHandler.java#L86
`
 final MessageDigest md = MessageDigest.getInstance(passwordScheme);
`
This is correct.

https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/auth/AbstractCompareAuthenticationHandler.java#L95
`
String.format("{%s}%s", passwordScheme, LdapUtils.base64Encode(hash)).getBytes());
`
This is not considered when the passwordScheme contains the '-' character.

Ref:
https://tools.ietf.org/id/draft-stroeder-hashed-userpassword-values-01.html

For example:

On LDAP Server,store userPassword (encode by SHA-256) format is:
{SHA256}BsSOzvGznv4K7yvNA9vnqI701/MSMd/fyNcfNy07YN0=

({HASH_NAME_WITHOUT '-'} + BASE64(HASH))

**Comment by serac** [comment]
Just tying to clarify the usage @binsys would need with the fix proposed in #122.

    final CompareAuthenticationHandler handler = new CompareAuthenticationHandler();
    handler.setPasswordScheme("SHA256:SHA-256");

Is that correct?

**Comment by dfish3r** [comment]
That's what I had in mind. No API breakage, but still no first class support for salted hashes.
