### ISSUE TITLE
How to change password of active directory

### ISSUE THREAD

**Issue by hbrls** [vt-middleware/ldaptive#130]
There are 2 types of change password: 1) `CHANGE_PASSWORD` with knowing the old password, 2) `RESET_PASSWORD` without the old but be authorized to do so.

As far as I can search from the web, active directory does not support `CHANGE_PASSWORD`. And the [line](https://github.com/vt-middleware/ldaptive/blob/master/integration/src/test/java/org/ldaptive/extended/PasswordModifyOperationTest.java#L79) from the test cases seems to proving it.

If let every user could `RESET_PASSWORD`, they can reset **each other**'s password.

I also found that active directory has a `SELF` group that can restrict that user could only reset his own password, by logon to *Windows Administrator* and right click blabla. But I did not find a way to edit that `SELF` settings by `ldaptive`.

How do you guys implement `CHANGE_PASSWORD` for active directory? Thanks.

**Comment by dfish3r** [comment]
I believe this thread has the answer to your question:

https://groups.google.com/forum/#!topic/ldaptive/lK08V3l9DCY

**Comment by hbrls** [comment]
@dfish3r awesome!

FYI. The key is to do a `DELETE` and `ADD` in a single modification.

```
modify.execute(new ModifyRequest(dn,
    new AttributeModification(AttributeModificationType.REMOVE, new UnicodePwdAttribute(oldPassword)),
    new AttributeModification(AttributeModificationType.ADD, new UnicodePwdAttribute(newPassword))));
```

**Comment by thiagowallass** [comment]
I did exactly as above, a `REMOVE` and a `ADD` in a single modification using the `UnicodePwdAttribute`, but I received the following error: 

`[LDAP: error code 16 - 00002085: AtrErr: DSID-031525C6, #1:  0: 00002085: DSID-031525C6, problem 1001 (NO_ATTRIBUTE_OR_VAL), data 0, Att 9005a (unicodePwd):len 22]`

Does it have something with encoding? Someone can help me?

**Comment by dfish3r** [comment]
You might have a schema problem, but my first guess is that you need to bind with credentials that allow you to modify the `unicodePwd` attribute.
