### ISSUE TITLE
active directory objectguid returns different by java 7/8

### ISSUE THREAD

**Issue by hbrls** [vt-middleware/ldaptive#133]
The code is:

```java
String[] FIELDS = { "objectGUID", ... };
Authenticator auth;

AuthenticationRequest req = new AuthenticationRequest(username, new Credential(password), FIELDS);
AuthenticationResponse resp = auth.authenticate(req);
LdapEntry entry = resp.getLdapEntry();

entry.getAttribute("objectGuid").getBinaryValue(); // <----
```

The last line returns different `byte[]` by java 7/8.

And as I break  point into it:

```java
// /org/ldaptive/provider/jndi/JndiConnection.java

final JndiSearchIterator i = new JndiSearchIterator(request);
i.initialize();  // <---- I think this is the line that really does the search action
```

The result of `i` of `byte[]` is different already. And I think it's the line of this issue.

I currently could not make a public reproduce of the issue. But it's reproducible with my env and ad server.

May this screenshot helps:

![wechatimg322](https://user-images.githubusercontent.com/1220476/33889164-3dfb3282-df8a-11e7-80a7-738d46e01f45.jpeg)

**Comment by dfish3r** [comment]
You have to indicate which attributes are binary.
A simple solution for your use case is to configure the `SearchEntryResolver` to use the `ObjectGuidHandler` class.
If you really want the data as bytes, you can then use `GlobalIdentifier#toBytes` to convert it back.

FYI ldaptive 1.2.x doesn't support Java 7.

**Comment by hbrls** [comment]
I'm using 1.1.0. So should I upgrade it first?

**Comment by dfish3r** [comment]
I would recommend you upgrade.
You'll still see the same issue with regards to declaring binary attributes.

**Comment by hbrls** [comment]
Thanks, `ObjectGuidHandler` fixed my problems. 

My code was wrong but it returned a consistent uuid so that I thought it was correct. Java 7/8 somehow raised the wrong code.

FYI, the correct code is:

```
// for auth
SearchEntryResolver resolver = new SearchEntryResolver();
resolver.setSearchEntryHandlers(new ObjectGuidHandler());
auth.setEntryResolver(resolver);

// or for search
SearchResult result = executor.search(cf, new SearchFilter(filter), fields, new ObjectGuidHandler()).getResult();
```

The result of the above correct code will return THE SAME OBJECTGUID you would see in Windows admin panel.
