### ISSUE TITLE
Incorrect base DN escaping in SearchOperation::executeSearch

### ISSUE THREAD

**Issue by gagarski** [vt-middleware/ldaptive#144]
I am using Apereo CAS which uses Ldaptive for LDAP authentication. Maybe I am wrong but it seems to me that Ldaptive behaves incorrectly when I am doing LDAP search with baseDN containing escaped characters.

I did some research and found out that the search ends up with the following on the call stack:
```
search:341, PartialCompositeDirContext (com.sun.jndi.toolkit.ctx)
search:807, JndiConnection$JndiSearchIterator (org.ldaptive.provider.jndi)
initialize:735, JndiConnection$JndiSearchIterator (org.ldaptive.provider.jndi)
search:463, JndiConnection (org.ldaptive.provider.jndi)
executeSearch:103, SearchOperation (org.ldaptive)
```

Let's start from the bottom:

#### executeSearch:103, SearchOperation (org.ldaptive)

Here I have the following string in `request.baseDn`: 
```
CN=John Doe,OU=Dept \"ACME\",OU=Subdept \"ACME\",OU=x,OU=y,OU=z,DC=test,DC=dc
```

This string is properly escaped to pass as baseDn to LDAP search operation.

#### search:463, JndiConnection (org.ldaptive.provider.jndi)

Same here. Properly escaped name is in request.baseDn

#### initialize:735, JndiConnection$JndiSearchIterator (org.ldaptive.provider.jndi)

Nothing new, `this.request.baseDn` (the same value passed to the iterator constructor) is unchanged.

#### search:807, JndiConnection$JndiSearchIterator (org.ldaptive.provider.jndi)

Here we pass `sr.baseDn` to `ctx.search` and...

#### search:341, PartialCompositeDirContext (com.sun.jndi.toolkit.ctx)

... this function creates `CompositeName` from the passed `baseDn`. The `CompositeName` constructor seems to remove the escaping from the DN and then the wrong search with unescaped DN is performed:

```
CN=John Doe,OU=Dept "ACME",OU=Subdept "ACME",OU=x,OU=y,OU=z,DC=test,DC=dc
```

My Microsoft AD server returns an error response and the search operation is failed.

I am not quite sure but it seems related to #119 for me. Probably we should create an `LdapName` object from `baseDn` in `search:807, JndiConnection$JndiSearchIterator (org.ldaptive.provider.jndi)
`

**Comment by dfish3r** [comment]
I've confirmed this bug and agree with your analysis.

**Comment by dfish3r** [comment]
Try the latest snapshot and let me know if that resolves your issue.

**Comment by gagarski** [comment]
Sorry for the late pingback: I've updated my CAS installation and therefore ldaptive. It seems like the issue is resolved, I was able to remove my local workarounds. Thanks!
