### ISSUE TITLE
NettyUtils.shutdownGracefully does not allow user to check if the underlying EventLoopGroup finished shut down or not

### ISSUE THREAD

**Issue by leeyc0** [vt-middleware/ldaptive#174]
According to https://netty.io/4.0/api/io/netty/util/concurrent/EventExecutorGroup.html#shutdownGracefully, user should check the returned Future to confirm if the shutdown operation finished or not. This is critical for Thread synchronization and proper resource cleanup at program shut down.

Currently NettyUtils.shutdownGracefully simply ignores the returned Future and have no way to check if the EventLoopGroup finished shut down or not.

**Comment by dfish3r** [comment]
Added listener to emit a log reporting on the success of the shutdown.

**Comment by leeyc0** [comment]
It is not enough. I need a **synchronous** method, or at least, a synchronization API to wait.

**Comment by dfish3r** [comment]
What behavior are you seeing that is requiring you to wait for the thread pools to shutdown? The underlying threads are daemons, they should not disrupt a JVM exit.

**Comment by leeyc0** [comment]
When it deploys in a servlet server (for example tomcat), servlet servers expects the threads to shut down before it destroys the servlet context, otherwise such error emits:
`
WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [xxxx] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread`

It is possible to undeploy a servlet application without shutting tomcat completely. I am not sure it is an issue or not, but we should enforce good programming habit by waiting the threads to die before  servlet application undeploys. As such we need a synchronization API to wait.

**Comment by dfish3r** [comment]
Ah, the Tomcat classloading memory leak. I've done all my testing with Jetty and I haven't seen any shutdown problems yet.

I think making `close` synchronous is the best choice here; I prefer the parity the `open` in that regard.
This issue made me investigate whether netty supported a zero length quiet period and it does.
Since no new tasks can be submitted when shutdown is invoked, this avoids unnecessary blocking during `close`.

**Comment by dfish3r** [comment]
Can you test your patch with the latest snapshot published here:

https://github.com/vt-middleware/maven-repo

**Comment by leeyc0** [comment]
Thanks, let me to report to the maintainer. I am just an outsider that only attempting to fix those thread leaks.

**Comment by leeyc0** [comment]
Looks like works as intended. Thanks.

**Comment by leeyc0** [comment]
BTW the document should be updated. The method is synchronous now.
(https://www.ldaptive.org/javadocs/org/ldaptive/transport/netty/NettyUtils.html#shutdownGracefully(io.netty.channel.EventLoopGroup))
