### ISSUE TITLE
ldaptive 2.0.0 regression issue with Fast Bind authentication request and response diagnostic message data

### ISSUE THREAD

**Issue by atzoum** [vt-middleware/ldaptive#182]
Hi,
We are facing a possible regression after switching from ldaptive 1.3.0 (using unboundid provider) to ldaptive 2.0.0 when we try to authenticate with wrong credentials using Fast Bind.
More specifically, the diagnostic message contained in the response always comes with 0 (zero) data and therefore `ActiveDirectoryAuthenticationResponseHandler` cannot parse the `ActiveDirectoryAccountState#Error` properly.

I tried to prepare some sample code which reproduces the error, unfortunately you still need to start your own Active Directory instance in order to run it.
After running the main class contained in [FastBindZeroDataBug.zip](https://github.com/vt-middleware/ldaptive/files/5373714/FastBindZeroDataBug.zip) we are getting the following output
```
Using JNDI with Fast Bind: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
Using Ldaptive 2.0.0 without Fast Bind: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
Using Ldaptive 2.0.0 with Fast Bind: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 0, v1db1
```

It is clear from the above example that when we are using Fast Bind we are getting `data 0`, whereas in all other cases we are getting `data 52e`.

Unfortunately it is practically impossible to further debug the issue since it appears to be related with some low-level DER parsing/decoding or even lower (netty?).

**Comment by dfish3r** [comment]
If you could run the "Ldaptive 2.0.0 with Fast Bind" test and enable the following logging:
`io.netty.handler.logging.LoggingHandler=DEBUG`
`org.ldaptive=DEBUG`

That log output should give me enough information to troubleshoot. Thanks.

**Comment by atzoum** [comment]
Here you go: [fastbind.log](https://github.com/vt-middleware/ldaptive/files/5374057/fastbind.log)

**Comment by atzoum** [comment]
Closing this issue, as it appears we were not really using Fast Bind in ldaptive 1.3.0 since we were using a `BindAuthenticationHandler` instead of a `PooledBindAuthenticationHandler`. 
After switching to a `PooledBindAuthenticationHandler` in ldaptive 1.3.0 we are experiencing the same behaviour (data 0).

**Comment by dfish3r** [comment]
Based on the logs you posted the directory is sending back `data 0`.
```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 30 84 00 00 00 66 02 01 02 61 84 00 00 00 5d 0a |0....f...a....].|
|00000010| 01 31 04 00 04 56 38 30 30 39 30 33 30 38 3a 20 |.1...V80090308: |
|00000020| 4c 64 61 70 45 72 72 3a 20 44 53 49 44 2d 30 43 |LdapErr: DSID-0C|
|00000030| 30 39 30 33 41 39 2c 20 63 6f 6d 6d 65 6e 74 3a |0903A9, comment:|
|00000040| 20 41 63 63 65 70 74 53 65 63 75 72 69 74 79 43 | AcceptSecurityC|
|00000050| 6f 6e 74 65 78 74 20 65 72 72 6f 72 2c 20 64 61 |ontext error, da|
|00000060| 74 61 20 30 2c 20 76 31 64 62 31 00             |ta 0, v1db1.    |
+--------+-------------------------------------------------+----------------+
```
So I don't think there is a parsing bug here. It's likely that AD doesn't support these response codes when using Fast Bind.
