### ISSUE TITLE
Missing HostnameVerifyingTrustManager per docs

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#183]
Per the docs:

> If you have a implementation of javax.net.ssl.TrustManager it can be added directory to SslConfig. Ldaptive provides several implementations which may be helpful:
> AggregateTrustManager - combines multiple trust managers allowing the use of all trust managers or any trust manager to pass validation
> DefaultTrustManager - the default JVM trust managers
> HostnameVerifyingTrustManager - custom trust manager based on certificate hostname
> AllowAnyTrustManager - trusts any client or server

`HostnameVerifyingTrustManager` appears to be missing/invalid, and should be removed from the docs possibly.

I can certainly send a pull request to update the docs, if you'd point out where the docs are.

**Comment by dfish3r** [comment]
Yep, looks like I missed that, PR would be great.
Docs can be found here: https://github.com/vt-middleware/ldaptive/tree/gh-pages/docs/guide

Note that hostname verification is now handled as a separate concern, so the `HostnameVerifyingTrustManager` was removed. Looks like I did add a section for that.

**Comment by mmoayyed** [comment]
Sounds good, thanks much. PR upcoming.
