### ISSUE TITLE
Review pool log levels

### ISSUE THREAD

**Issue by dfish3r** [vt-middleware/ldaptive#19]
The connection pool emits errors for each connection that fails on #initialize.
Given the nature of pools, it may be incorrect to consider that an error.

Review current log levels and adjust accordingly.

**Comment by dfish3r** [comment]
Any periodic tasks should emit logs at trace level.

**Comment by serac** [comment]
Perhaps a logging engine message diagnostic context can help inform loggers about the calling context, e.g. background or foreground thread.

**Comment by serac** [comment]
It would be helpful to log pool growth and shrinkage events at a more prominent log level, e.g. INFO or WARN, to facilitate performance tuning.
