### ISSUE TITLE
Not all user attributes are returned

### ISSUE THREAD

**Issue by alexantonica** [vt-middleware/ldaptive#195]
I'm trying to retrieve all user attributes regardless of them being populated or not in the AD. 
From what i can see it should return all of them ,which are around 50+
but i'm only getting around 20.

```       SearchOperation searchOp = new SearchOperation(connection);
            SearchRequest searchReq = new SearchRequest();
            searchReq.setSearchEntryHandlers(new ObjectSidHandler(), new ObjectGuidHandler());
            searchReq.setBaseDn(ldapConfiguration.getBaseDN());
            searchReq.setSearchFilter(new SearchFilter("(objectClass=user)"));
            searchReq.setReturnAttributes(ReturnAttributes.ALL.value());
            Response<SearchResult> searchResultResponse = searchOp.execute(searchReq);
```
I'm using 1.2.4 version

Am i missing something?

**Comment by dfish3r** [comment]
You may need to bind as a certain principal in order to read all those attributes. Are you configuring a `BindConnectionInitializer`?

**Comment by alexantonica** [comment]
> You may need to bind as a certain principal in order to read all those attributes. Are you configuring a `BindConnectionInitializer`?

Hi @dfish3r thank you for the reply. Yes, i'm using the `BindConnectionInitializer` with admin credentials

**Comment by dfish3r** [comment]
You may want to put the `org.ldaptive.provider` package in TRACE to confirm what results are coming back from the directory.

If you could post the results of the same search using `ldapsearch` to confirm which attributes are coming back, that would also be helpful.

**Comment by dfish3r** [comment]
Any update on this issue?

**Comment by alexantonica** [comment]
Sorry didn't have time to try what you suggested.Please give ma a couple more days.

**Comment by dfish3r** [comment]
Closing this for now. Feel free to reopen when you have time to investigate.
