### ISSUE TITLE
ModifyRequest.Builder methods misspelled

### ISSUE THREAD

**Issue by ceharris** [vt-middleware/ldaptive#199]
All overloads of `modificiations` [sic] in `ModifyRequest.Builder`have a misspelled name. Perhaps avoid a breaking change by introducing correctly-spelled methods and deprecating the existing methods?

**Comment by dfish3r** [comment]
Deprecated the old methods, but I think the next release will be `2.1.0`. The deprecated methods will likely be removed at that point.
