### ISSUE TITLE
Licensing is unclear

### ISSUE THREAD

**Issue by hyandell** [vt-middleware/ldaptive#201]
Hi vt-middleware,

The licensing is stated on the site to be:

"This project is dual licensed under both the LGPL and Apache 2."

Can you confirm that you mean that the license is "LGPL (any version) OR Apache-2.0"? There is considerable debate in the industry as to whether the phrase dual-licensed means OR or AND, so I want to make sure I am understanding your intentions correctly. I didn't see a previous issue on this topic of what dual-licensed means, but my apologies if I missed one.

**Comment by dfish3r** [comment]
Thanks @hyandell . License page updated.
