### ISSUE TITLE
Dns Srv record lookup change in behavior between v1.2 and v2

### ISSUE THREAD

**Issue by xweskingx** [vt-middleware/ldaptive#203]
In version 1.2 of ldaptive, the DefaultConnectionStrategy deferred to jndi for resolving ldap urls.

Using an ldap url such as "ldap://DC=mycompany,DC=org" would use the com.sun.jndi.ldap.ServiceLocator, to convert the ldap url to a dns url "dns:///_ldap._tcp.mycompany.org", and eventually resolve to the DNS Srv record.

After upgrading to version 2 of ldaptive, the default connection strategy is ActivePassiveConnectionStrategy, which does not appear to use the jndi name lookup. 

To address this, it's required to specify the DnsSrvConnectionStrategy when building the connection config.

Unfortunately the DnsSrvConnectionStrategy expects a url in the format "dns://hostname/domain?record" which would look something like "dns:///mycompany.org?_ldap._tcp" for the above example. This requires first converting the ldap url to the dns url manually before building the ldaptive connection config.

It would be nice if the DnsSrvConnectionStrategy would also accept ldap urls of the form "ldap(s):///<ldap dc path>" .

It would also be nice if the default connection strategy would fallback to DnsSrv when ActivePassiveStrategy fails due to no host specified.

This is the behavior of other ldap tools such as the open ldap ldapsearch utility: 

> [ldapsearch] allows you to specify an LDAP URL without the host or port but that uses a base DN that uses only “dc” components (with special characters escaped, like %3D in place of an equal sign and %2C in place of a comma) to indicate that the tool should request the “_ldap._tcp” record for the specified domain (for example, “-H ldap:///dc%3Dexample%2Cdc%3Dcom” will cause it to look up the SRV records for “_ldap._tcp.example.com” and select an appropriate server from that response).

**Comment by dfish3r** [comment]
Thanks for this report. At first glance this feature seems reasonable. I'll review https://datatracker.ietf.org/doc/html/draft-ietf-ldapext-locate-08 and attempt a patch for `DnsSrvConnectionStrategy`.

I'll likely spawn a second issue to evaluate changing the default connection strategy or the behavior of `ActivePassiveConnectionStrategy`.

**Comment by dfish3r** [comment]
@xweskingx can you try the latest snapshot and confirm it resolves this issue? Thanks.

**Comment by dfish3r** [comment]
No response from reporter.
