### ISSUE TITLE
Ldaptive 2.1.1 release timeline

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#204]
Hello, It looks like when used in the context of a Spring BOM, conflicts show up between netty versions used by ldaptive 2.1.0 and Spring Boot 2.6.3, the latter forcing a higher netty version that is now used only in ldaptive's master branch. Is there a projected timeline for the 2.1.1 release line to include support for the newer netty versions? I see 2.1.0 was released quite a while ago so this may be a good time to cut a patch release.

**Comment by dfish3r** [comment]
I'm hoping for this month.

Do you use a maven enforcer that prevents these sorts of BOM problems?

**Comment by dfish3r** [comment]
2.1.1 released.
