### ISSUE TITLE
Cannot get the Enable property from Active Directory

### ISSUE THREAD

**Issue by lixingbest** [vt-middleware/ldaptive#207]
Hello everyone, I'm syncing from Active Directory, but can't get the AD domain user's enabled property, my code is as follows:
 
SearchOperation search = new SearchOperation(
                    DefaultConnectionFactory.builder()
                            .config(ConnectionConfig.builder()
                                    .url(config.getSyncUrl())
                                    .connectionInitializers(BindConnectionInitializer.builder()
                                            .dn(config.getAdminName())
                                            .credential(config.getAdminPasswd())
                                            .build())
                                    .build())
                            .build(),
                    ouObj.getDn());

SearchResponse response = search.execute(config.getUserFilterExpr());

**Comment by dfish3r** [comment]
What exception are you seeing? `DEBUG` logs are generally helpful in diagnosing issues.

**Comment by dfish3r** [comment]
No response from reporter. Feel free to reopen if you have something more to report.
