### ISSUE TITLE
Deprecate individual methods from org.ldaptive.DnParser ?

### ISSUE THREAD

**Issue by ilgrosso** [vt-middleware/ldaptive#214]
With 2.1.1 the class [org.ldaptive.DnParser](https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/DnParser.java) was completely deprecated.

The new `org.ldaptive.dn.DnParser` interface and its `DefaultDnParser` implementation, though, are not replacing the whole set of static utility methods available with the deprecated class above.

Would it be possible to either move the `@deprecated` annotation to method level or instead provide a non-deprecated alternative for static methods as `DnParser#substring`?

**Comment by dfish3r** [comment]
I believe this would be the new syntax:
```
Dn mydn = new Dn(...);
String startingAtIndex1 = mydn.subDn(1).format();
```
Note that you can pass an `RDnNormalizer` to the format method if desired.

**Comment by ilgrosso** [comment]
Thank you @dfish3r it worked like a charm :+1:
