### ISSUE TITLE
[Question/Feature Request] Turn off follow referrals? 

### ISSUE THREAD

**Issue by scrawfor99** [vt-middleware/ldaptive#223]
Hi, 

I have been looking through the documentation on the ldaptive website, but could not find an answer so wanted to ask directly. 
Is it possible to configure a searchReferenceHandler so that it does not follow referrals? There are options for configuring the search depth and limit, but I do not see any API functionality for preventing the automated following of referrals--i.e. simply stopping a connection instead of getting partial connections when an AD LDAP server.

If I have missed something please let me know.

Thank you!

**Comment by dfish3r** [comment]
By default references are not followed, you have to configure a `FollowSearchResultReferenceHandler` to get that behavior. If you just need to inspect the references they are available at `SearchResponse#getReferences`

**Comment by scrawfor99** [comment]
Thank you!
