### ISSUE TITLE
LDAP queries are blocked by grow method

### ISSUE THREAD

**Issue by lixelu** [vt-middleware/ldaptive#224]
Hi, 

We had a situation in which part of a pool of connections was valid and the other was invalid because of ldap certificate expiration. grow() method was called and it started to recreate connections. SSL connections creation was failing because of the expired certificate, unfortunately within about 2 seconds each. The process being serialised it took more than 60 seconds for the grow() method to finish, during this time having the poolLock aquired and all queries being blocked. The server was under heavy load and the service became unresponsive for that period of time.

I saw in this recent issue https://github.com/vt-middleware/ldaptive/pull/218 "Fix potential long waits on checkout." that a similar problem was raised and a fix was approved, but I think my problem would still occur. poolLock.lock() is called before while (currentPoolSize < size && count < size * 2) and createAvailableConnection() which is the potential long operation.

Is there a better way to use the validate & grow operations on the pool without stopping all queries?

Thanks, 
Alex

**Comment by dfish3r** [comment]
I agree that delays in connection creation will impact performance and the patch you reference would exacerbate those problems.

What values are you using for `ConnectionConfig#connectTimeout` and `SslConfig#handshakeTimeout` ?

**Comment by lixelu** [comment]
We are currently using v1.2.4 of ldaptive and we don't have SslConfig#handshakeTimeout as a config option. So probably that falls back to a default.
ConnectionConfig#connectTimeout is set at 5000ms.

**Comment by dfish3r** [comment]
@lixelu I pushed a fixed for this. Feel free to review, but the upshot is that the longest wait from grow should now be the time it takes for *2* sequential connection failures.

**Comment by dfish3r** [comment]
Closing this out, feel free to reopen.
