### ISSUE TITLE
Performing LDAP queries via Oracle's JNDI interface, but using ldaptive under the hood

### ISSUE THREAD

**Issue by defacto64** [vt-middleware/ldaptive#226]
Hi,

is it possible to perform LDAP queries using the normal Oracle's JNDI interface (i.e. via javax.naming.directory.DirContext) but with ldaptive as the real LDAP provider under the hood?

If so, would anyone kindly provide a working example?

TIA

**Comment by dfish3r** [comment]
Sorry, not possible.
