### ISSUE TITLE
Empty org.ldaptive.schema.Schema instance

### ISSUE THREAD

**Issue by wirepatch** [vt-middleware/ldaptive#232]
I'm accessing an OpenLdap server using `org.ldaptive.schema.SchemaFactory`:

```
final SearchResponse response = new SearchOperation(factory, request).execute("objectClass=*");

if (!response.getEntries().isEmpty()) {

   for (final LdapEntry entry : response.getEntries()) {
       final Schema schema = SchemaFactory.createSchema(entry);
```

Server objects are being read showing expected results. However the resulting 'Schema' instance is being created but all internal collections remain empty i.e. it does not contain any schema info at all. 

Access is by full admin privileges. Using the very same credentials Apache Directory Studio displays the expected full range of schema info.

**Comment by dfish3r** [comment]
The `Schema` object is built using attributes from the `subschema` entry. I can't tell from what you've posted if that is available in the search response. Try creating the `Schema` using:
```
SchemaFactory.createSchema(factory);
```
which will retrieve the rootDSE and then retrieve the subschema entry.

**Comment by wirepatch** [comment]
Many thanks for your swift reply! 🥳 That's the line of code I was unable to find in the Ldaptive user guide.
