### ISSUE TITLE
SearchOperation.execute() try-with-resources breaks OpenLDAP paging

### ISSUE THREAD

**Issue by johnellinwood** [vt-middleware/ldaptive#239]
### Overview
PagedResultsClient doesn't work with OpenLDAP. The SearchOperation.execute() methods all use a try-with-resources loop on a new connection returned from the connection factory. This results in a new connection being created for every execute method call, which is then closed after that operation is completed.  The PagedResultClient uses the execute method to retrieve pages in separate executions. This results in every page request being made with a different connection.  The cookie returned from OpenLDAP is only valid on a single connection.  The same code works fine on Exchange ldap, but not on OpenLDAP.

### Environment
Using Java 17 with SpringBoot. LDAP server is OpenLDAP.

### Expect
I expect PagedResultsClient to retrieve all pages of data from an OpenLDAP server successfully.

### Actual
First page returns data and a cookie.  Next page I get a PROTOCOL_ERROR response and no result entries.

### Fix
Need a SearchOperation.execute() method that allows external connection management, and doesn't try to close the connection after each execution.  Or some other way to keep an actual single connection across all paging requests.

**Comment by dfish3r** [comment]
Are you using a `SingleConnectionFactory` with the `PagedResultsClient`?

**Comment by dfish3r** [comment]
Thanks for the explanation. I made an update to the docs to emphasize the constraints.
