### ISSUE TITLE
AllowAnyHostnameVerifier

### ISSUE THREAD

**Issue by mikkamax** [vt-middleware/ldaptive#247]
Hello! I'm trying to do something as simple as that:

```
     val connectionConfig = ConnectionConfig.builder()
            .url("ldaps://my-ldap-server.loc:636")
            .sslConfig(
                SslConfig.builder()
                    .trustManagers(MyTrustManager())
                    .hostnameVerifier(AllowAnyHostnameVerifier())
                    .build()
            )
            .build()
        
        val connectionFactory = DefaultConnectionFactory.builder()
            .config(connectionConfig)
            .build()

        val tempConnection = connectionFactory.connection
        tempConnection.open()
        tempConnection.close()
```

So, I'm using my own trust manager with my own root certificate to trust the server. And I don't want to verify server hostname, because it has misspel in its certificate.

When I'm trying to connect to the server, establishing server trust is ok, but after that I'm getting following error:
"javax.net.ssl.SSLException: javax.net.ssl.SSLHandshakeException: Hostname verification failed for my-ldap-server.loc using org.ldaptive.ssl.DefaultHostnameVerifier@37b071a8"

So, even though I supplied AllowAnyHostnameVerifier in ConnectionConfig it still tries to use DefaultHostnameVerifier for some reason, which is why I can't establish the connection.

Am I doing something wrong?

Thanks!

**Comment by dfish3r** [comment]
If your custom `TrustManager` is not of type `X509ExtendedTrustManager`, ldaptive will inject a `DefaultHostnameVerifier` to ensure that hostname verification occurs.

**Comment by mikkamax** [comment]
Thank you for your reply (and awesome library))!

I wrapped trust managers containing my certificate and jvm certificates in AggregateTrustManager, and now everything seems to be working as expected with server name verification.
