### ISSUE TITLE
UnboundIDProvider does not support the cipher suites/protocol property

### ISSUE THREAD

**Issue by Lasering** [vt-middleware/ldaptive#39]
In the UnboundIDProvider.getConnectionFactory(final ConnectionConfig cc) there is the following code:

    if (cc.getSslConfig() != null &&
        cc.getSslConfig().getEnabledCipherSuites() != null) {
      throw new UnsupportedOperationException(
        "UnboundID provider does not support the cipher suites property");
    }
    if (cc.getSslConfig() != null &&
        cc.getSslConfig().getEnabledProtocols() != null) {
      throw new UnsupportedOperationException(
        "UnboundID provider does not support the protocols property");
    }

**Which is not true.** UnboundID (at least in version 2.3.8) fully supports EnabledCipherSuites and Protocols (and with some effort random number generators as well).

**Comment by dfish3r** [comment]
Confirmed. Looks like UnboundID has supported this since 2.3.5.
