### ISSUE TITLE
 manager.merge multi value attribute

### ISSUE THREAD

**Issue by sysmat** [vt-middleware/ldaptive#51]
I'm working on glassfish application and when I'm trying to add attribute mobile I'm getting:

 exception=[org.ldaptive.LdapException@1173492716::resultCode=ATTRIBUTE_OR_V
ALUE_EXISTS, matchedDn=null, responseControls=null, referralURLs=null, messageId=-1, providerException=javax.naming.directory.AttributeInUseException: [LDAP: error code 20 - Attribute Or Value Exists]
; remaining name 'eduPersonPrincipalName=tmica@guest.arnes.si,dc=guest,dc=arnes,dc=si']

but if I use the same code in command line it works fine, is there any issue with using same conection on glassfish application server.

I can not find issue.

Regards, Tomaz

**Comment by sysmat** [comment]
In my application I bind with root user and doing attribute changes on different users in LDAP.

1) Should after merge I call  close on connection?

2) If two application user doing on concurrent user I get this exception?
So one application user should unbind(close connecton) to work properly.

Regards, Tomaz

**Comment by dfish3r** [comment]
> 1) Should after merge I call close on connection?
That's not necessary to complete the merge. Without knowing more about your application I can't say whether it will help your concurrency issues.

> 2) If two application user doing on concurrent user I get this exception?
If you want to avoid the exception you'll have to introduce a lock so you're not modifying the same user with different threads. Or you can catch and ignore the exception if you're confident some other thread has already persisted the data correctly.

**Comment by sysmat** [comment]
The LDAP: error code 20 - Attribute Or Value Exists is causing attribute nsAccountLock if for user is set I can not use merge even if I'm changing only mail, very strange.

Bean:
---------
@Entry(
  dn = "distinguishedName", // this can be a property in your object or a hard coded string
  attributes = {   
    @Attribute(name = "eduPersonPrincipalName", property = "eduPersonPrincipalName"),
    @Attribute(name = "mail", property = "mails"),
    @Attribute(name = "mobile", property = "mobiles"),   
    @Attribute(name = "uid", property = "username"),
    @Attribute(name = "userPassword", property = "userPassword", binary = true),
    @Attribute(name = "nsAccountLock", property = "lock"),   
....


private String[] lock = new String[0];
....
@JsonProperty("nsAccountLock")
    public String[] getLock() {
        return lock;
    }
    public void setLock(String[] lock) {
        this.lock = lock;
    }

Scenario 1:
--------------
When this nsAccountLock is not present in LDAP then I can modify any attribute whit out problem.

Scenario 2:
--------------
When this nsAccountLock is present in LDAP then I can not modify any attribute(error code 20 - Attribute Or Value Exists )

Regards, Tomaz

**Comment by dfish3r** [comment]
It sounds like your directory does not allow modifies on an entry if that account is locked.
(At least for the user you are binding as.)
You may need to unlock the account, perform the modify, and then lock the account is get the behavior you want.

**Comment by dfish3r** [comment]
No further feedback from reporter.
