### ISSUE TITLE
release

### ISSUE THREAD

**Issue by sysmat** [vt-middleware/ldaptive#55]
When is plan to release version 1.1.0 ?

Regards, Tomaž

**Comment by dfish3r** [comment]
October 1 if I can get my ducks in a row.

**Comment by mmoayyed** [comment]
Yay. Look fwd to it.

**Comment by ernieKovak** [comment]
Go, ducks!

**Comment by mmoayyed** [comment]
@dfish3r Hope things are ok with the ducks :)

**Comment by dfish3r** [comment]
1.0.7 is out the door. Working on 1.1.0.

**Comment by dfish3r** [comment]
1.1.0 is tagged. I struggled a bit with creating the repository bundle for a multi module project, but it should go smoother next time.

Documentation updates will take a few days to get in order. The website is moving from google sites to github pages.
