### ISSUE TITLE
Feature request to support Durations

### ISSUE THREAD

**Issue by tomzeller** [vt-middleware/ldaptive#58]
Hi, how about a feature request for ldaptive to support Durations ?

"blockWaitTime in IdPv3 ldap.properties"
http://shibboleth.net/pipermail/users/2015-November/025164.html

"Incorrect idp.pool.LDAP.validatePeriod property format"
http://shibboleth.net/pipermail/users/2015-November/025528.html

**Comment by dfish3r** [comment]
The Duration annotation lives in the java-support project. That would give ldaptive a dependency on an external library that doesn't exist in maven central.

Is there another annotation, perhaps in the javase, that could be used?

**Comment by mmoayyed** [comment]
Would @Size work? Most Durations I know of are concrete classes, and live in the javax caching API or in JDK8. JDK8 probably is the best option, but that does require, well, JDK8 :)

**Comment by dfish3r** [comment]
I'm planning to move to JDK8 very soon.

**Comment by mmoayyed** [comment]
Good on you :) Possible timeline?

**Comment by dfish3r** [comment]
Resolved in merge #77

**Comment by tomzeller** [comment]
Nice !

I don't think there is a related issue for the Shibboleth IdP to incorporate this, is that something you can handle too Daniel ?
