### ISSUE TITLE
inconsistent null password handling from Credential object

### ISSUE THREAD

**Issue by frett** [vt-middleware/ldaptive#68]
I'm seeing an NPE from: `new Credential((String) null)` but not from `new Credential((byte[]) null)`. There is also explicit checking for a null password in a `Credential` object here: https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/auth/Authenticator.java#L275 but the code here would throw an NPE for a null password: https://github.com/vt-middleware/ldaptive/blob/master/core/src/main/java/org/ldaptive/auth/AbstractCompareAuthenticationHandler.java#L60

I'm mostly looking for clarification if the `Credential` object should or shouldn't support null passwords so I know if I need to patch this here or in the CAS `LdapAuthenticationHandler`

**Comment by dfish3r** [comment]
> I'm seeing an NPE from: new Credential((String) null) but not from new Credential((byte[]) null).

`Credential` stores the password as a byte array, the NPE comes from converting the string to bytes.

> There is also explicit checking for a null password in a Credential object here:

See my comments below.

> but the code here would throw an NPE for a null password:

It would, but as you noted `Authenticator` does explicit null checking.

> I'm mostly looking for clarification if the Credential object should or shouldn't support null passwords 

It allows null passwords in the general case. There may be some use case or provider interaction for that behavior for general LDAP operations. However, in the authentication API a null or empty password is not considered valid input.

**Comment by frett** [comment]
alright, I'll avoid trying to create a `Credential` object when we have a null password internally in CAS.
