### ISSUE TITLE
Publish snapshots to Sonatype

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#71]
Testing the current master would be tremendously easier if ldaptive were to publish snapshots to sonatype. I can provide instructions and/or do the work, if you need an extra hand.

**Comment by mmoayyed** [comment]
If this is done, at least CAS would be able to automatically test the changes that are published without any manual work. Collaboration would be that much faster.

**Comment by dfish3r** [comment]
I have sonatype credentials, but have never integrated publishing into the build.
Instructions would be helpful.

**Comment by mmoayyed** [comment]
First step is, you will need to encrypt your credentials via Travis, and put them into a Travis file:
https://github.com/Jasig/cas/blob/4.1.x/.travis.yml

See those SECURE entries for instance.

Your credentials need to match a settings.xml file that is used by the sonatype deployment task:
https://github.com/Jasig/cas/blob/4.1.x/travis/settings.xml

So when you encrypt, you need to provide SONATYPE_USER=username and SONATYPE_PWD=password to the Travis command.

You'll need to have Travis installed locally of course. See instructions at the top of the yml file.

Then you instruct Travis to call a shell script to push changes to sonatype:
https://github.com/Jasig/cas/blob/4.1.x/travis/deploy-to-sonatype.sh

**Comment by mmoayyed** [comment]
You can of course do all of this by hand manually, but letting Travis do this would be automatic and somewhat immediate.

**Comment by dfish3r** [comment]
Can you articulate the reasons why the sonatype repository is preferred over:
https://github.com/vt-middleware/maven-repo

Is it just about reducing the number of repository dependencies?

**Comment by mmoayyed** [comment]
That, and sonatype auto publishes to central. This allows me to auto switch a GA to a SNAPSHOT without any further changes in the poms, which is much easier to teach. If a bug is fixed and the snapshot is made available automatically, I can just go back to my pom, switch the version and rebuild the same exact way without any additional changes.

**Comment by dfish3r** [comment]
Can you post a link to one of your poms that configures the sonatype repo?

**Comment by mmoayyed** [comment]
https://github.com/Jasig/cas-overlay-template/blob/master/pom.xml

**Comment by mmoayyed** [comment]
Specifically:

```
<repositories>
        <repository>
            <id>sonatype-releases</id>
            <url>http://oss.sonatype.org/content/repositories/releases/</url>
        </repository>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>
```

The "releases" bit arguably can be removed.

**Comment by dfish3r** [comment]
So it's not like sonatype is detecting whether you're asking for a snapshot or a release and silently redirecting you.
You still have to configure multiple repositories.

**Comment by mmoayyed** [comment]
Correct.

**Comment by mmoayyed** [comment]
So Daniel, would you want me to submit a PR to handle the sonatype/Travis changes?

**Comment by mmoayyed** [comment]
Tried out the snapshot. Works great! thanks. Sorry I missed your earlier post on this.

**Comment by mmoayyed** [comment]
So, I apologize for being this demanding but this still not solved. 

If I let travis pull the repository above and run through the tests, it fails miserable. 
If I download and install ldaptive into my local repo and then run through tests, everything passes fine. 

So, this sort of indicates to me that snapshots are not auto-published, right? State of the codebase is not the same of the repo. I don't know if you can all this a snapshot. 

If you are manually publishing artifacts every once in a while, you're really releasing milestones. Which doesn't solve the problem stated in the original issue description.

Are there processes in place that publish snapshots to the github repo automatically?

**Comment by dfish3r** [comment]
Updated ldaptive with travis config.
Snapshots are now being published to our repository automatically.

**Comment by mmoayyed** [comment]
Very nice. Thank you.
