### ISSUE TITLE
Allow retry behavior config via namespaces

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#79]
Is it possible to configure a retry behavior via namespaces? I fail to see an option that would allow me to configure retries and wait times between retries. It appears that by default, some form of retry is activated, but it would also be good to have control over that setting.

**Comment by dfish3r** [comment]
Updated v2 to support all options in `ConnectionConfig`.
Including `autoReconnectCondition` which allows custom implementation of retry and backoff.
