### ISSUE TITLE
Deadlock in ldaptive + CAS 4

### ISSUE THREAD

**Issue by jinowolski** [vt-middleware/ldaptive#81]
We have experienced deadlocks in our CAS service configured with ldaptive as LDAP connector. It appears to be related to keeping pool locked while performing connection validation. Deadlocks was present in CAS 4.0.1 and 4.2.0 which corresponds to ldaptive versions 1.0.3 and 1.1.0.

In attached jstack, a lot of threads are waiting for the lock <0x000000070f847368> which is owned by Thread-11 daemon performing connection validation.

**[jstack-20160326-1751.txt](https://github.com/vt-middleware/ldaptive/files/191125/jstack-20160326-1751.txt)** (ldaptive 1.1.0, CAS 4.2.0)

While trying to resolve (or at least hotfix) problem I've noticed several things:

- deadlock is more likely to occur when using BlockingConnectionPool rather than SoftLimitConnectionPool
- deadlock is more likely to occur when maximum pool size is greater
- I've tried to force duration of validation to be shorter by adding `-Dcom.sun.jndi.ldap.read.timeout=1000` to Tomcat parameters, but it didn't help
- before deadlock, number of threads grows gradually over about two hours. When it reaches some level (~200 waiting / ~260 total), the tomcat server hangs out

Currently we have the following settings which appears to be quite stable (deadlock occurs rarely):

- validateOnCheckout = false
- **validatePeriodically = true**
- **validatePeriod = 300 (seconds)**
- minPoolSize = 3
- maxPoolSize = 10 [raising to 100 is likely to reproduce problem]
- connectTimeout = 3000 (milliseconds)
- responseTimeout = 3000 (milliseconds)
- blockWaitTime = 3000 (milliseconds)
- idleTime = 600 (seconds)

Part of the cas deployerConfixContext.xml with ldaptive configuration:

    <bean id="authenticator" class="org.ldaptive.auth.Authenticator"
        c:resolver-ref="dnResolver"
        c:handler-ref="authHandler" />

    <bean id="dnResolver" class="org.ldaptive.auth.PooledSearchDnResolver"
        p:baseDn="${ldap.baseDn}"
        p:subtreeSearch="true"
        p:allowMultipleDns="false"
        p:connectionFactory-ref="searchPooledLdapConnectionFactory"
        p:userFilter="${ldap.authn.searchFilter}" />

    <bean id="searchPooledLdapConnectionFactory"
        class="org.ldaptive.pool.PooledConnectionFactory"
        p:connectionPool-ref="searchConnectionPool" />

    <bean id="searchConnectionPool" parent="abstractConnectionPool" />

    <bean id="abstractConnectionPool" abstract="true"
        class="org.ldaptive.pool.SoftLimitConnectionPool" 
        init-method="initialize"
        p:poolConfig-ref="ldapPoolConfig"
        p:blockWaitTime="${ldap.pool.blockWaitTime}"
        p:validator-ref="searchValidator"
        p:pruneStrategy-ref="pruneStrategy"
        p:connectionFactory-ref="connectionFactory" />

    <bean id="ldapPoolConfig" class="org.ldaptive.pool.PoolConfig"
        p:minPoolSize="${ldap.pool.minSize}"
        p:maxPoolSize="${ldap.pool.maxSize}"
        p:validateOnCheckOut="${ldap.pool.validateOnCheckout}"
        p:validatePeriodically="${ldap.pool.validatePeriodically}"
        p:validatePeriod="${ldap.pool.validatePeriod}" />

    <bean id="connectionFactory" class="org.ldaptive.DefaultConnectionFactory"
        p:connectionConfig-ref="connectionConfig" />

    <bean id="connectionConfig" class="org.ldaptive.ConnectionConfig"
        p:ldapUrl="${ldap.url}"
        p:connectTimeout="${ldap.connectTimeout}"
        p:responseTimeout="${ldap.responseTimeout}"
        p:useStartTLS="${ldap.useStartTLS}"
        p:sslConfig-ref="sslConfig" />

    <bean id="sslConfig" class="org.ldaptive.ssl.SslConfig">
        <property name="credentialConfig">
            <bean class="org.ldaptive.ssl.X509CredentialConfig"
                p:trustCertificates="${ldap.trustedCert}" />
        </property>
    </bean>

    <bean id="pruneStrategy" class="org.ldaptive.pool.IdlePruneStrategy"
        p:prunePeriod="${ldap.pool.prunePeriod}"
        p:idleTime="${ldap.pool.idleTime}" />

    <bean id="searchValidator" class="org.ldaptive.pool.SearchValidator" />

    <bean id="authHandler" class="org.ldaptive.auth.PooledBindAuthenticationHandler"
        p:connectionFactory-ref="bindPooledLdapConnectionFactory" />

    <bean id="bindPooledLdapConnectionFactory"
        class="org.ldaptive.pool.PooledConnectionFactory"
        p:connectionPool-ref="bindConnectionPool" />

    <bean id="bindConnectionPool" parent="abstractConnectionPool" />

JVM: openjdk-7-jdk:amd64 7u95-2.6.4-1~deb8u1

Any help with resolving this issue will be appreciated.

**Comment by dfish3r** [comment]
Is this reproducible on the Oracle JVM?

**Comment by serac** [comment]
Note this thread of the attached dump file:

    "Thread-11" daemon prio=10 tid=0x00007f7c28176800 nid=0x5871 in Object.wait() [0x00007f7c3235d000]
       java.lang.Thread.State: WAITING (on object monitor)
      at java.lang.Object.wait(Native Method)
      - waiting on <0x00000007154e4918> (a com.sun.jndi.ldap.LdapRequest)
      at java.lang.Object.wait(Object.java:503)
      at com.sun.jndi.ldap.Connection.readReply(Connection.java:481)
      - locked <0x00000007154e4918> (a com.sun.jndi.ldap.LdapRequest)
      at com.sun.jndi.ldap.LdapClient.getSearchReply(LdapClient.java:640)
      at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:563)
      at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1986)
      at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1848)
      at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1773)
      at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:386)
      at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:356)
      at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:339)
      at org.ldaptive.provider.jndi.JndiConnection$JndiSearchIterator.search(JndiConnection.java:806)
      at org.ldaptive.provider.jndi.JndiConnection$JndiSearchIterator.initialize(JndiConnection.java:735)
      at org.ldaptive.provider.jndi.JndiConnection.search(JndiConnection.java:463)
      at org.ldaptive.SearchOperation.executeSearch(SearchOperation.java:103)
      at org.ldaptive.SearchOperation.invoke(SearchOperation.java:85)
      at org.ldaptive.SearchOperation.invoke(SearchOperation.java:15)
      at org.ldaptive.AbstractOperation.execute(AbstractOperation.java:126)
      at org.ldaptive.pool.SearchValidator.validate(SearchValidator.java:82)
      at org.ldaptive.pool.SearchValidator.validate(SearchValidator.java:20)
      at org.ldaptive.pool.AbstractPool.validate(AbstractPool.java:210)
      at org.ldaptive.pool.AbstractConnectionPool.validate(AbstractConnectionPool.java:747)
      at org.ldaptive.pool.AbstractConnectionPool$3.run(AbstractConnectionPool.java:289)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
      at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)

       Locked ownable synchronizers:
      - <0x000000070f847368> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
      - <0x000000070fb7b0f8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

That looks like it may be the thread that owns the lock on which others are blocked, `0x000000070f847368`, and it appears itself to be blocked on IO. If that analysis is correct, then it may indicate an ldaptive concurrency bug. A blocked worker thread belonging to the pool should not hold the pool lock on a pending IO operation.

**Comment by jinowolski** [comment]
In term of checking Oracle JVM - I've switched yesterday to Oracje Java 8u77 and increased maximum number of connections in a pool to 100 to recreate likely lock conditions. As for now everything looks good. There are a lot of waiting/parking threads, similar in number to that of our lock incidents, but they are irrelevant, only waiting in Tomcat TaskQueue. I'm afraid we have to just wait for possible failure.
It may be also possible, that Oracle JVM respects the `-Dcom.sun.jndi.ldap.read.timeout`, but OpenJDK doesn't (it should be already fixed in 6u29, so I expect it to be fixed in 7 too https://bugs.openjdk.java.net/browse/JDK-7094377) and we won't hit the deadlock quickly with Oracle JVM.

**Comment by dfish3r** [comment]
Look like the SearchValidator is hanging for some reason
```
  - waiting on <0x00000007154e4918> (a com.sun.jndi.ldap.LdapRequest)
  at java.lang.Object.wait(Object.java:503)
  at com.sun.jndi.ldap.Connection.readReply(Connection.java:481)
```

Setting a response timeout is what uses `com.sun.jndi.ldap.read.timeout`. I don't believe you can pass that property into the JVM with the `-D` switch. But your 3000ms should be honored since you are setting responseTimeout.

So it's not clear to me why your directory is hanging on the rootDSE search. I'll do some testing and see if I can reproduce. We may need a feature request to kill the validator thread if it's deadlocking the pool. On the other hand that may just hide poor directory performance and/or poor configuration.

**Comment by dfish3r** [comment]
@jinowolski did you see a deadlock on the Oracle JVM?

**Comment by jinowolski** [comment]
Haven't seen, but it is non-deterministic, may happen sooner or later. As for now looks stable.

**Comment by magicknot** [comment]
I'm also experiencing a deadlock using BlockingConnectionPool. Even when using a pool with minimum and maximum size of 1. I'll try using Oracle JVM and report back.

**Comment by magicknot** [comment]
@dfish3r sorry for the late answer, but using Oracle JVM I'm also facing this issue.

**Comment by dfish3r** [comment]
@magicknot can you post your configuration?

**Comment by dfish3r** [comment]
Pushed to 1.0.x at: https://sourceforge.net/p/ldaptive/code/3159/

**Comment by dfish3r** [comment]
Both the 1.2.x and 1.0.x snapshots have potential fixes for this.
