### ISSUE TITLE
Release ldaptive v1.2

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#82]
Placeholder to track the release status of ldaptive v1.2.

**Comment by mmoayyed** [comment]
Daniel, do you have a sense of when you might be able to release 1.2? I am specifically interested in the fix suggested in this issue report https://github.com/vt-middleware/ldaptive/issues/88 We have it successfully working with the SNAPSHOT and I am wondering schedule-wise when I might be able to recommend switching to the GA.

**Comment by dfish3r** [comment]
Next week if the stars align.
It's long overdue.

**Comment by mmoayyed** [comment]
Thanks. If it's any consolation, I have done extensive testing on 1.2 and have deployed the snapshot a few times to get some fixes in place. No reported issues, yet! 

Great work.

**Comment by dfish3r** [comment]
1.2 released.
