### ISSUE TITLE
Preserve BC when handling timeouts in v1.2

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/ldaptive#95]
Timeout values in v.1.2 appear to be using Durations. Great. For backwards compatibility, it would be nice to employ logic similar to this:

1. If the value provided is a numeric, assume it's in milliseconds (or whatever it was before durations) and translate it to Duration
2. Otherwise, expect a duration

Not a big deal, but it would be nice.

**Comment by dfish3r** [comment]
I am supporting both on the 1.0.x branch, but no plans to do so on 1.2.x.
